# Generated by Django 4.1.3 on 2022-11-15 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_about_options_alter_about_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
