# Generated by Django 4.1.3 on 2022-11-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_team_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='title',
            field=models.CharField(blank=True, help_text='Optional', max_length=100, null=True),
        ),
    ]
